### ISSUE TITLE
Multi threading support

### ISSUE THREAD

**Issue by brauliobo** [chanks/sequel-advisory-locking#1]
With multiple threads, the unlock can't happen as the connection used might be different from the one use to create the lock

**Comment by chanks** [comment]
This gem wraps Sequel’s built-in connection pool, so I don’t believe this
should happen. Have you actually experienced this or are you just worried
it might happen?

**Comment by brauliobo** [comment]
yes it happenned, see the sequel issue at https://github.com/jeremyevans/sequel/issues/1879

**Comment by chanks** [comment]
This gem uses `synchronize` internally (https://github.com/chanks/sequel-advisory-locking/blob/master/lib/sequel/extensions/advisory_locking.rb#L22), so if you're passing in a block to the advisory_lock function then you should get the expected behavior. If you're not using a block, then I guess it's on the caller to ensure that they're already within a Sequel `synchronize` block.

If I were publishing this gem again I think I'd tweak the API to require a block, but I guess it's a bit late for that. I'd say if you plan on using it, always pass a block to the function, and if not, then make sure you're using a `synchronize` block outside your calls. I think that's a thing people should have in mind anyway when they're using connection-specific Postgres features, like advisory locks or notifications.

**Comment by brauliobo** [comment]
hmm interesting @chanks, thanks for the explanation. in our case, we lock multiple rows' ids through a dataset similar to what is done at https://stackoverflow.com/a/4582994/670229.

so it seems this approach causes more issues, as several threads are then processing the locked rows.

closing for now as it isn't a real issue on this gem
